title: DimoGame Privacy Policy
description: Privacy Policy for DimoGame - Memory Game
baseurl: ""
url: "https://dayeneris.github.io/DimoGame_privacy-policy"

theme: minima

contact_email: dayeneriss.apps@gmail.com
